language: python
# Python < 3.7 not supported as it doesn't support circlualr imports binding
# to a name see
# https://bugs.python.org/issue30024
python:
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=caspy/
after_success:
  - coveralls
